### ISSUE TITLE
您好，能把训练好的model.pth分享一下吗，想用这个去试试迁移学习，万分感谢~

### ISSUE THREAD

**Issue by KmustXH** [xming521/CTAI#10]

**Comment by kanghu-bo** [comment]
from data_set import make 请问这行模块您怎么解决的呢？

**Comment by KmustXH** [comment]
没解决啊，这个应该是作者写的代码，我也在问他能不能把这部分代码发出来


| |
熊航
|
|
邮箱：xh970307@163.com
|

签名由 网易邮箱大师 定制

在2020年10月27日 15:04，kanghu-bo 写道：

from data_set import make 请问这行模块您怎么解决的呢？

**Comment by kanghu-bo** [comment]
> 没解决啊，这个应该是作者写的代码，我也在问他能不能把这部分代码发出来 | | 熊航 | | 邮箱：xh970307@163.com | 签名由 网易邮箱大师 定制 在2020年10月27日 15:04，kanghu-bo 写道： from data_set import make 请问这行模块您怎么解决的呢？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

可以联系上吗？

**Comment by KmustXH** [comment]
他没回我


| |
熊航
|
|
邮箱：xh970307@163.com
|

签名由 网易邮箱大师 定制

在2020年10月27日 15:08，kanghu-bo 写道：

没解决啊，这个应该是作者写的代码，我也在问他能不能把这部分代码发出来 | | 熊航 | | 邮箱：xh970307@163.com | 签名由 网易邮箱大师 定制 在2020年10月27日 15:04，kanghu-bo 写道： from data_set import make 请问这行模块您怎么解决的呢？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

可以联系上吗？

**Comment by kanghu-bo** [comment]
> 他没回我 | | 熊航 | | 邮箱：xh970307@163.com | 签名由 网易邮箱大师 定制 在2020年10月27日 15:08，kanghu-bo 写道： 没解决啊，这个应该是作者写的代码，我也在问他能不能把这部分代码发出来 | | 熊航 | | 邮箱：xh970307@163.com | 签名由 网易邮箱大师 定制 在2020年10月27日 15:04，kanghu-bo 写道： from data_set import make 请问这行模块您怎么解决的呢？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 可以联系上吗？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

有消息麻烦共享下哈,谢谢~

**Comment by tebderfiit** [comment]
请问你拿到模型了吗？

**Comment by xming521** [comment]
> 请问你拿到模型了吗？

我建议重新训练模型
