### ISSUE TITLE
ModuleNotFoundError: No module named 'net'

### ISSUE THREAD

**Issue by zi1zi** [xming521/CTAI#14]
您好，把训练好的模型放在CTAI_flask中报错ModuleNotFoundError: No module named 'net'

**Comment by xming521** [comment]
正常应该不会吧，你在哪运行的，建议用命令行运行

**Comment by zi1zi** [comment]
![图片](https://user-images.githubusercontent.com/48040139/223611828-33d22c78-8228-4492-badd-b905319fc71a.png)
![图片](https://user-images.githubusercontent.com/48040139/223610977-f7463fb5-32ce-44c9-a5ee-b6f933d8cd3d.png)
我是用你提供的数据集跑的模型，就只跑了一轮(测试一下，先把这个项目跑起来)，中间注释了一段，不注释的话会报错，然后保存了模型。去CTAI_flask跑就出现了下面那个图的错误

**Comment by xming521** [comment]
应该是你保存自己模型的时候没完整保存，还需要这个net，这个net应该是你训练自己模型时候的文件，需要复制过来

**Comment by zi1zi** [comment]
对的，我就把我自己训练的模型复制过去了，我是只训练了一次模型，中间还把plt那几行代码注释掉了，要不报错，数据集就用您提供的那个，你感觉是有啥问题吗，您可以给我提供给我一个训练好的模型吗，我想试试模型的整体部署落地

**Comment by kaiwen-says** [comment]
一样的错误

**Comment by kaiwen-says** [comment]
![Uploading 屏幕截图 2024-09-05 234638.png…]()

**Comment by CaptainYa** [comment]
> 您好，把训练好的模型放在CTAI_flask中报错ModuleNotFoundError: No module named 'net'

您好可以联系下吗

**Comment by CaptainYa** [comment]
> 一样的错误

你解决了吗
