### ISSUE TITLE
csv

### ISSUE THREAD

**Issue by Peolibar** [xming521/CTAI#15]

**Comment by Peolibar** [comment]
csv_file = open('../data/all/res.csv', 'w', encoding='gbk', newline='')
df = pd.read_csv('../data/all/临床数据.csv', encoding='gbk')
请问这两个地方的csv文件在哪里呀？

**Comment by xming521** [comment]
不好意思我也找不到了，应该是些无关紧要的信息

**Comment by Peolibar** [comment]
> 

捉！那请问cv这个模块下面的脚本是什么作用呢？有点没搞明白整个系统的联系
