### ISSUE TITLE
请问要cuda，tensorrt跟pycuda的版本是什么

### ISSUE THREAD

**Issue by ruodasucheng** [xming521/CTAI#18]
请问要cuda，tensorrt跟pycuda的版本是什么

**Comment by xming521** [comment]
不好意思我后面torch升级了cuda版本应该不对，但是tensorrt是 8.5.1.7是确定的

**Comment by ruodasucheng** [comment]
好的谢谢，方便再问一下torch的版本吗

**Comment by xming521** [comment]
我也记不大清了 你先试一下1.11.0吧  ，可以的话再给我留个言

**Comment by ruodasucheng** [comment]
我试了1.10.0可以用

**Comment by MyGubooy** [comment]
> 我试了1.10.0可以用

您好 您跑通了 可以给个联系方式请教一下吗~~
