### ISSUE TITLE
项目中的TensorRT是如何使用的？

### ISSUE THREAD

**Issue by crazy-zxx** [xming521/CTAI#24]
请问该项目中的TensorRT是如何使用的？

**Comment by crazy-zxx** [comment]
> 先运行CTAI/CTAI_tensorRT/to_oonx.py 转为oonx 再运行CTAI/CTAI_tensorRT/main.py 优化模型

感谢，但是我发现在flask后端的app.py中是直接加载的pth模型，所以并没使用onnx的模型吧

**Comment by xming521** [comment]
是的目前还没用
