### ISSUE TITLE
求数据集

### ISSUE THREAD

**Issue by liwenhaode** [xming521/CTAI#4]
你好  模型中的训练集在网上可以找到吗 方便提供数据集训练下吗   我的邮箱是 liwenbest@163.com

**Comment by xming521** [comment]
https://share.weiyun.com/5eS2jDk

**Comment by Peolibar** [comment]
> https://share.weiyun.com/5eS2jDk

你好，请问一下这个数据集是还要自己划分训练集和测试集吗？

**Comment by xming521** [comment]
> [Peolibar](/Peolibar)

是需要自己划分的

**Comment by Peolibar** [comment]
> > [Peolibar](/Peolibar)
> 
> 是需要自己划分的

谢谢回答！麻烦再问一下数据集里的动脉相和静脉相有什么作用呢？这个数据集划分的标准是什么？

**Comment by xming521** [comment]
> > > [Peolibar](/Peolibar)
> > 
> > 
> > 是需要自己划分的
> 
> 谢谢回答！麻烦再问一下数据集里的动脉相和静脉相有什么作用呢？这个数据集划分的标准是什么？
动脉静脉我当时是只用了其中一个，就随机按比例随机划分就行

**Comment by Peolibar** [comment]
> 动脉静脉我当时是只用了其中一个，就随机按比例随机划分就行

好滴好滴！感谢回答！

**Comment by TiaVicone** [comment]
您好，请问前端页面是不见了嘛`(*>﹏<*)′

**Comment by CuiLilucy** [comment]
您好，可以求一下数据集吗？非常感谢！ cuililucy@168.com
